# Generated by Django 2.1.1 on 2018-09-20 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180917_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 6, 27, 57, 843480, tzinfo=utc)),
        ),
    ]
