# Generated by Django 2.1.1 on 2018-09-20 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180920_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 8, 11, 22, 678490, tzinfo=utc)),
        ),
    ]
