# Generated by Django 2.1.1 on 2018-09-20 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180920_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 22, 11, 3, 47, 543053, tzinfo=utc)),
        ),
    ]
