# Generated by Django 2.1.1 on 2018-09-24 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180920_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 10, 55, 5, 950340, tzinfo=utc)),
        ),
    ]
