# Generated by Django 2.1.1 on 2018-10-04 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180924_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 6, 8, 16, 29, 904712, tzinfo=utc)),
        ),
    ]
