# Generated by Django 2.1.1 on 2018-10-10 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20181010_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 9, 34, 44, 871199, tzinfo=utc)),
        ),
    ]
