# Generated by Django 2.1.1 on 2018-10-10 11:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20181010_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 12, 11, 11, 41, 14395, tzinfo=utc)),
        ),
    ]
