# Generated by Django 2.1.1 on 2018-09-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180906_0734'),
        ('order', '0002_auto_20180831_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='prs',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
